// lib/mock-data.ts
import { Banner } from "@/types";

export const CATEGORIES = [
  {
    id: "1",
    name: "Смартфоны",
    slug: "smartphones",
    icon: "📱",
    description: "Флагманы и бюджетники",
    product_count: 240,
    image: "/categories/phones.jpg",
  },
  {
    id: "2",
    name: "Ноутбуки",
    slug: "laptops",
    icon: "💻",
    description: "Для работы и игр",
    product_count: 180,
    image: "/categories/laptops.jpg",
  },
  {
    id: "3",
    name: "Бытовая техника",
    slug: "appliances",
    icon: "🏠",
    description: "Умный дом",
    product_count: 320,
    image: "/categories/appliances.jpg",
  },
  {
    id: "4",
    name: "Наушники",
    slug: "headphones",
    icon: "🎧",
    description: "Hi-Fi и TWS",
    product_count: 95,
  },
  {
    id: "5",
    name: "Планшеты",
    slug: "tablets",
    icon: "📟",
    description: "iPad и Android",
    product_count: 60,
  },
  {
    id: "6",
    name: "Игры",
    slug: "gaming",
    icon: "🎮",
    description: "Консоли и аксессуары",
    product_count: 150,
  },
];

export const BANNERS: Banner[] = [
  {
    id: "1",
    title: "iPhone 16 Pro Max",
    subtitle: "Мощь titanium. Камера профессионала.",
    badge: "НОВИНКА",
    cta: "Купить сейчас",
    href: "/product/1",
    bg_gradient: "from-slate-900 via-blue-950 to-slate-900",
    accent_color: "#3B82F6",
    tag: "от 189 990 ₸",
  },
  {
    id: "2",
    title: "MacBook Pro M4",
    subtitle: "Производительность нового уровня.",
    badge: "ХИТ ПРОДАЖ",
    cta: "Смотреть",
    href: "/product/2",
    bg_gradient: "from-gray-900 via-zinc-900 to-gray-900",
    accent_color: "#22C55E",
    tag: "от 579 990 ₸",
  },
  {
    id: "3",
    title: "Samsung Galaxy S25",
    subtitle: "AI-камера. Snapdragon 8 Elite.",
    badge: "СКИДКА 20%",
    cta: "Узнать больше",
    href: "/product/3",
    bg_gradient: "from-indigo-950 via-purple-950 to-slate-900",
    accent_color: "#A78BFA",
    tag: "от 149 990 ₸",
  },
];

export const PRODUCTS = [
  {
    id: "1",
    name: "iPhone 16 Pro Max 256GB",
    slug: "iphone-16-pro-max-256",
    description:
      "Флагман Apple с чипом A18 Pro, камерой 48 Мп и дисплеем 6.9 дюймов Super Retina XDR. Титановый корпус, Action Button, USB-C.",
    price: 189990,
    old_price: 219990,
    images: ["/products/iphone16pm.jpg"],
    category_id: "1",
    brand: "Apple",
    rating: 4.9,
    review_count: 2341,
    in_stock: true,
    is_new: true,
    is_featured: true,
    specs: {
      Процессор: "Apple A18 Pro",
      Дисплей: "6.9\" Super Retina XDR",
      Камера: "48 Мп + 48 Мп + 12 Мп",
      Батарея: "4685 мАч",
      Память: "256 ГБ",
    },
    created_at: "2024-09-20T00:00:00Z",
  },
  {
    id: "2",
    name: "MacBook Pro 16\" M4 Pro",
    slug: "macbook-pro-16-m4-pro",
    description:
      "Профессиональный ноутбук Apple с чипом M4 Pro, 24 ГБ RAM и дисплеем Liquid Retina XDR 16.2 дюйма.",
    price: 579990,
    images: ["/products/macbook-m4.jpg"],
    category_id: "2",
    brand: "Apple",
    rating: 4.8,
    review_count: 892,
    in_stock: true,
    is_featured: true,
    specs: {
      Процессор: "Apple M4 Pro",
      ОЗУ: "24 ГБ",
      Дисплей: "16.2\" Liquid Retina XDR",
      Батарея: "до 22 часов",
      Память: "512 ГБ SSD",
    },
    created_at: "2024-11-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    description:
      "Флагман Samsung с 200 Мп камерой, стилусом S Pen, Snapdragon 8 Elite и AI-функциями Galaxy AI.",
    price: 149990,
    old_price: 189990,
    images: ["/products/s25ultra.jpg"],
    category_id: "1",
    brand: "Samsung",
    rating: 4.7,
    review_count: 1543,
    in_stock: true,
    is_new: true,
    specs: {
      Процессор: "Snapdragon 8 Elite",
      Дисплей: "6.9\" Dynamic AMOLED",
      Камера: "200 Мп + 50 Мп + 10 Мп",
      Батарея: "5000 мАч",
    },
    created_at: "2025-01-15T00:00:00Z",
  },
  {
    id: "4",
    name: "Sony WH-1000XM6",
    slug: "sony-wh-1000xm6",
    description:
      "Премиальные беспроводные наушники с лучшим в классе шумоподавлением, 40 часов автономной работы.",
    price: 89990,
    old_price: 99990,
    images: ["/products/sony-wh.jpg"],
    category_id: "4",
    brand: "Sony",
    rating: 4.9,
    review_count: 3421,
    in_stock: true,
    specs: {
      Тип: "Полноразмерные",
      "АКБ": "до 40 часов",
      "Шумоподавление": "Да, адаптивное",
      Подключение: "Bluetooth 5.3",
    },
    created_at: "2025-03-01T00:00:00Z",
  },
  {
    id: "5",
    name: "ASUS ROG Zephyrus G16",
    slug: "asus-rog-zephyrus-g16",
    description:
      "Игровой ноутбук с RTX 4080, Intel Core Ultra 9, 32 ГБ RAM и дисплеем 240 Гц OLED.",
    price: 449990,
    images: ["/products/rog-g16.jpg"],
    category_id: "2",
    brand: "ASUS",
    rating: 4.8,
    review_count: 467,
    in_stock: true,
    specs: {
      GPU: "NVIDIA RTX 4080",
      CPU: "Intel Core Ultra 9",
      ОЗУ: "32 ГБ DDR5",
      Дисплей: "16\" OLED 240Гц",
    },
    created_at: "2024-10-10T00:00:00Z",
  },
  {
    id: "6",
    name: "Dyson V15 Detect",
    slug: "dyson-v15-detect",
    description:
      "Беспроводной пылесос с лазерным обнаружением пыли, HEPA-фильтрацией и 60 минутами работы.",
    price: 119990,
    old_price: 139990,
    images: ["/products/dyson-v15.jpg"],
    category_id: "3",
    brand: "Dyson",
    rating: 4.7,
    review_count: 2108,
    in_stock: true,
    specs: {
      Мощность: "240 Вт",
      Работа: "до 60 минут",
      Фильтрация: "HEPA",
      "Лазер": "Да",
    },
    created_at: "2024-08-20T00:00:00Z",
  },
  {
    id: "7",
    name: "iPad Pro 13\" M4",
    slug: "ipad-pro-13-m4",
    description:
      "Самый тонкий продукт Apple с чипом M4, дисплеем Ultra Retina XDR и поддержкой Apple Pencil Pro.",
    price: 259990,
    images: ["/products/ipad-pro.jpg"],
    category_id: "5",
    brand: "Apple",
    rating: 4.9,
    review_count: 1234,
    in_stock: true,
    is_new: true,
    specs: {
      Процессор: "Apple M4",
      Дисплей: "13\" Ultra Retina XDR",
      Память: "256 ГБ",
      "Толщина": "5.1 мм",
    },
    created_at: "2024-05-15T00:00:00Z",
  },
  {
    id: "8",
    name: "PlayStation 5 Pro",
    slug: "playstation-5-pro",
    description:
      "Игровая консоль нового поколения с улучшенным GPU, поддержкой 8K и PSSR-технологией масштабирования.",
    price: 199990,
    images: ["/products/ps5-pro.jpg"],
    category_id: "6",
    brand: "Sony",
    rating: 4.8,
    review_count: 5621,
    in_stock: false,
    is_featured: true,
    specs: {
      GPU: "AMD RDNA 3.5",
      Дисплей: "до 8K",
      Хранилище: "2 ТБ SSD",
      "PSSR": "Да",
    },
    created_at: "2024-11-07T00:00:00Z",
  },
];

export const FEATURED_PRODUCTS = PRODUCTS.filter((p) => p.is_featured);
